import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Source_Serif_4 } from 'next/font/google';
import Mainheading from "./sports/components/Mainheading";

const sourceSerif = Source_Serif_4({
  subsets: ['latin'],
  weight: ['400', '700'], // or any weights you need
  variable: '--font-source-serif',
  display: 'swap',
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sourceSerif.variable}>
      <head><link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-...your-integrity-hash..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        
          {/* _document.tsx or layout.tsx */}
            <script
              type="text/javascript"
              dangerouslySetInnerHTML={{
                __html: `
                  window._taboola = window._taboola || [];
                `,
              }}
            />
            <script src="https://cdn.taboola.com/libtrc/oahu-staradvertiser/loader.js" async></script>

        </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar/>
            <Mainheading/>
        {children}
        <Footer/>     
      </body>
    </html>
  );
}
